name: nodex_companion_app
description: A new Flutter project.
version: 1.0.0+1

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management & BLoC
  provider: ^5.0.0
  bloc: ^7.0.0-nullsafety.3
  flutter_bloc: ^7.0.0-nullsafety.5
  equatable: ^2.0.0

  # Fluro - Routing
  fluro: ^2.0.3

  # get_it - Service location
  get_it: ^7.1.3

  # Hive - database
  hive: ^2.0.0
  hive_flutter: ^1.0.0

  cupertino_icons: ^1.0.2

  rxdart: ^0.27.0

  path_provider: ^2.0.1
  heroicons: ^0.2.1

  # Desktop support
  desktop_window: ^0.4.0
  window_size:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size

  json_rpc_2: ^3.0.1
  web_socket_channel: ^2.1.0
  stream_channel: ^2.1.0
  shelf_web_socket: ^1.0.1
  shelf: ^1.1.4
  responsive_builder: ^0.4.1
  form_field_validator: ^1.1.0
  reactive_forms: ^10.4.1

  # JSON Annotation
  json_annotation: ^4.0.1
  flow_builder: ^0.0.2
  intl: ^0.17.0
  time: ^2.0.0
  jiffy: ^4.1.0

  # Algorand
  algorand_dart:
    path: ./../../algorand-dart/algorand_dart
  flutter_algosigner: ^0.0.2
  webview_flutter: ^2.0.9
  clipboard: ^0.1.3
  lottie: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Testing framework
  test: ^1.16.5

  # Build Runner & Source Generation
  build_runner: ^2.0.1

  # JSON serialization
  json_serializable: ^4.0.2

  # Hive generation
  hive_generator: ^1.0.0

  # Name & Launcher icons
  flutter_app_name: "^0.1.1"
  flutter_launcher_icons: "^0.9.0"

flutter:
  uses-material-design: true

  assets:
    - assets/animations/
    - assets/illustrations/
    - assets/icons/
    - assets/images/
    - assets/strings/
    - assets/security/

  fonts:
    - family: Public Sans
      fonts:
        - asset: assets/fonts/publicsans/PublicSans-Light.ttf
          weight: 300
        - asset: assets/fonts/publicsans/PublicSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/publicsans/PublicSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/publicsans/PublicSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/publicsans/PublicSans-Bold.ttf
          weight: 700
    - family: AlgorandIcons
      fonts:
        - asset: assets/icons/AlgorandIcons.ttf

flutter_app_name:
  name: "Algorand Node"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/ic_launcher.png"