name: nodex_server
description: A sample command-line application.
version: 1.0.0

# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  path: ^1.8.0

  # Hive - database
  hive: ^2.0.0

  # get_it - Service location
  get_it: ^7.1.3

  # RxDart
  rxdart: ^0.27.0

  # JSON RPC 2
  json_rpc_2: ^3.0.1

  # Shelf
  shelf: ^1.1.4
  shelf_web_socket: ^1.0.1

  # Stream Channels
  web_socket_channel: ^2.1.0
  stream_channel: ^2.1.0
  process_run: ^0.12.1
  system_info: ^1.0.0
  http: ^0.13.3

  # Algorand
  algorand_dart:
    git:
      url: git://github.com/RootSoft/algorand-dart.git
      ref: master
    #path: ./../../algorand-dart/algorand_dart

  # JSON Annotation
  json_annotation: ^4.0.1

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0

  # Build runner
  build_runner: ^2.0.5

  # JSON serialization
  json_serializable: ^4.0.2